# Generated by Django 4.0.4 on 2022-05-07 21:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ayushauth', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('medid', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 7, 21, 49, 29, 596283, tzinfo=utc))),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorid', to=settings.AUTH_USER_MODEL)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
